// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToFile(arg1:string,arg2:string):Promise<void>;

export function GetTlsFingerprint(arg1:string,arg2:string):Promise<string>;

export function LoadCollections():Promise<string>;

export function LoadHistory():Promise<string>;

export function LoadTlsTemplates():Promise<string>;

export function SaveCollection(arg1:string):Promise<void>;

export function SaveHistory(arg1:string):Promise<void>;

export function SaveTlsTemplates(arg1:string):Promise<void>;

export function SendRequest(arg1:string,arg2:string):Promise<string>;

export function SendRequestRepeat(arg1:string,arg2:string,arg3:number):Promise<string>;
