// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportToFile'](arg1, arg2);
}

export function GetTlsFingerprint(arg1, arg2) {
  return window['go']['main']['App']['GetTlsFingerprint'](arg1, arg2);
}

export function LoadCollections() {
  return window['go']['main']['App']['LoadCollections']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function LoadTlsTemplates() {
  return window['go']['main']['App']['LoadTlsTemplates']();
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SaveTlsTemplates(arg1) {
  return window['go']['main']['App']['SaveTlsTemplates'](arg1);
}

export function SendRequest(arg1, arg2) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2);
}

export function SendRequestRepeat(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequestRepeat'](arg1, arg2, arg3);
}
